"""
Django settings for task_manager project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
load_dotenv()
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["65.21.255.163", "127.0.0.1", "localhost", "atoms.is", "www.atoms.is"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',

    'daphne',  # Сервер для асинхронной обработки
    'django.contrib.staticfiles',
    'channels',

    'main_app',

    'django.contrib.sites',     # For allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    'rest_framework',
    'drf_spectacular',
    'rest_framework.authtoken',     # For tokens
    'dj_rest_auth',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'allauth.account.middleware.AccountMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Стандартный бекенд
    'allauth.account.auth_backends.AuthenticationBackend',  # Бекенд allauth
]

ROOT_URLCONF = 'task_manager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
                'main_app.context_processors.global_context',
                'main_app.context_processors.count_unread_comments',
                'main_app.context_processors.count_moderate_comments',
                'main_app.context_processors.companies_list',
            ],
        },
    },
]

WSGI_APPLICATION = 'task_manager.wsgi.application'

ASGI_APPLICATION = "task_manager.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'task_manager_db',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_L10N = True

USE_TZ = True
TIME_ZONE = 'Europe/Chisinau'

SITE_ID = 1     #allauth

FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100 MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100 MB

B2_BUCKET_NAME = "task-manager-storage-public"
B2_APPLICATION_KEY_ID = "003331a0fe0ce1d0000000003"
B2_APPLICATION_KEY = "K003wfQ+zgSnCx7g4Ww3vfeA7xgaxJQ"

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        "rest_framework.authentication.SessionAuthentication",  # Сессии
        "rest_framework.authentication.TokenAuthentication",  # Токены
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Настройки для регистрации/входа
ACCOUNT_AUTHENTICATION_METHOD = "username"  # Можно выбрать 'username', 'email' или 'username_email'

ACCOUNT_EMAIL_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = "optional"  # Варианты: 'mandatory', 'optional', 'none'

ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_SIGNUP_REDIRECT_URL = '/'  # Перенаправление после регистрации
ACCOUNT_LOGOUT_REDIRECT_URL = '/'  # Перенаправление после выхода
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 1

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT= os.path.join(BASE_DIR,'static/')

MEDIA_ROOT = os.path.join(BASE_DIR,'media/')  # Убедитесь, что путь корректный

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_COOKIE_NAME = 'sessionid'  # Название куки сессии
SESSION_COOKIE_AGE = 604800  # Время жизни сессии в секундах
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Сессия будет храниться после закрытия браузера
SESSION_COOKIE_SECURE = False  # Для работы на HTTP, не используйте True
SESSION_COOKIE_HTTPONLY = True  # Защищает от доступа JavaScript
